### ISSUE TITLE
[Bug] Voice Activity doesn't load

### ISSUE THREAD

**Issue by SKProCH** [Neodymium7/BetterDiscordStuff#22]
**Addon Name and Version**
VoiceActivity 1.4.1

**Discord Version**
Stable

**Describe the bug**
Plugin doesn't load on latest BetterDiscord
```
TypeError: Cannot read property 'Permissions' of undefined
    at Object.get DiscordPermissions [as DiscordPermissions] (betterdiscord://plugins/0PluginLibrary.plugin.js:408:151)
    at Object.value (betterdiscord://plugins/0PluginLibrary.plugin.js:2649:24)
    at Object.get (betterdiscord://plugins/0PluginLibrary.plugin.js:2633:26)
    at eval (betterdiscord://plugins/VoiceActivity.plugin.js:401:5)
    at eval (betterdiscord://plugins/VoiceActivity.plugin.js:1141:5)
    at buildPlugin (betterdiscord://plugins/VoiceActivity.plugin.js:1143:4)
    at eval (betterdiscord://plugins/VoiceActivity.plugin.js:1148:46)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.reloadAddon (<anonymous>:4:10047)
    at AsyncFunction.<anonymous> (<anonymous>:4:7387)
```

**To Reproduce**
Install (or update) BD and install plugin

**Comment by Neodymium7** [comment]
Yep, this is known. I assume you didn’t see any of the updates in the BetterDiscord server or my server, so here was my announcement:

![7FED872E-94EB-4847-9365-5EDEA03CC3F1](https://user-images.githubusercontent.com/68879269/193367810-ed570145-ba08-4fa3-9efe-c06557528e20.jpeg)

I’ll keep this issue open for now and close it once I’m able to get VoiceActivity fixed.

**Comment by SKProCH** [comment]
Oh, i really doesn't see any messages, sorry. Thanks for help!
