### ISSUE TITLE
[Bug] VoiceActivity crashes PTB when show a private group

### ISSUE THREAD

**Issue by Lusiiky** [Neodymium7/BetterDiscordStuff#61]
**Addon Name and Version**
VoiceActivity 1.8.13

**Discord Version**
_Discord Info_
ptb 278528 (85f5bf2) Host 1.0.1062 x64 (45361) Windows 11 64-bit (10.0.22631)

_BetterDiscord_
stable 1.10.1

**Describe the bug**
Discord PTB crashes if the plugin is activated and show a private group.

**To Reproduce**
Show/Click on a private group.

**Video**
https://youtu.be/F7d9cU0oiEw

**Additional context**
All plugins are deactivated, except VoiceActivity.

**Logs when crash**
```
VM2499 47470.91c2d89ebc10ef7a8bdd.js:1 TypeError: e is not a function
    at v.render (29062.db61dff280e6672933d4.js:1:883969)
    at i_ (94128.eec22c41764c4b44fa70.js:1:871247)
    at iy (94128.eec22c41764c4b44fa70.js:1:871045)
    at u (94128.eec22c41764c4b44fa70.js:1:912516)
    at sI (94128.eec22c41764c4b44fa70.js:1:894551)
    at 94128.eec22c41764c4b44fa70.js:1:894417
    at sH (94128.eec22c41764c4b44fa70.js:1:894425)
    at sT (94128.eec22c41764c4b44fa70.js:1:891176)
    at sx (94128.eec22c41764c4b44fa70.js:1:891565)
    at r6 (94128.eec22c41764c4b44fa70.js:1:840200)
    at 94128.eec22c41764c4b44fa70.js:1:907078
    at sR (94128.eec22c41764c4b44fa70.js:1:907083)
    at sD (94128.eec22c41764c4b44fa70.js:1:890453)
    at L (94128.eec22c41764c4b44fa70.js:1:960556)
    at E (94128.eec22c41764c4b44fa70.js:1:961086)
    at L.<computed> (94128.eec22c41764c4b44fa70.js:1:112369)
    at T (94128.eec22c41764c4b44fa70.js:1:112122)
    at MessagePort.Y (94128.eec22c41764c4b44fa70.js:1:112181)
(anonymous) @ VM2499 47470.91c2d89ebc10ef7a8bdd.js:1
o5 @ 94128.eec22c41764c4b44fa70.js:1
o.componentDidCatch.n.callback @ 94128.eec22c41764c4b44fa70.js:1
aK @ 94128.eec22c41764c4b44fa70.js:1
iX @ 94128.eec22c41764c4b44fa70.js:1
e @ 94128.eec22c41764c4b44fa70.js:1
(anonymous) @ 94128.eec22c41764c4b44fa70.js:1
sR @ 94128.eec22c41764c4b44fa70.js:1
sx @ 94128.eec22c41764c4b44fa70.js:1
r6 @ 94128.eec22c41764c4b44fa70.js:1
(anonymous) @ 94128.eec22c41764c4b44fa70.js:1
sR @ 94128.eec22c41764c4b44fa70.js:1
sD @ 94128.eec22c41764c4b44fa70.js:1
L @ 94128.eec22c41764c4b44fa70.js:1
E @ 94128.eec22c41764c4b44fa70.js:1
L.<computed> @ 94128.eec22c41764c4b44fa70.js:1
T @ 94128.eec22c41764c4b44fa70.js:1
Y @ 94128.eec22c41764c4b44fa70.js:1
```

**Comment by ghost** [comment]
Also happens on Canary.
