### ISSUE TITLE
VoiceActivity Could not be compiled [Bug]

### ISSUE THREAD

**Issue by TheGreatTaz** [Neodymium7/BetterDiscordStuff#65]
**Addon Name and Version**
VoiceActivity
v1.8.17

**Discord Version**
Stable

**Describe the bug**
An error was encountered while trying to load this plugin.

**To Reproduce**
launch discord

**Additional context**
```
Error: Module 'canViewChannel' not found.
	
	Contact the plugin developer to inform them of this error.
    at expectModule (betterdiscord://plugins/VoiceActivity.plugin.js:215:11)
    at eval (betterdiscord://plugins/VoiceActivity.plugin.js:294:26)
    at buildPlugin (betterdiscord://plugins/VoiceActivity.plugin.js:1293:4)
    at eval (betterdiscord://plugins/VoiceActivity.plugin.js:1298:46)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

**Comment by Monk3yBuns** [comment]
same trouble
