### ISSUE TITLE
ActivityIcons Could not be compiled [Bug]

### ISSUE THREAD

**Issue by ErFuyl** [Neodymium7/BetterDiscordStuff#66]
**Addon Name and Version**
ActivityIcons v1.4.4

**Discord Version**
stable 303105 (1897d8a) Host 0.0.57 x64 Build Override: N/A Linux 64-bit (5.15.0-112-generic)

**Describe the bug**
The plugin fails to load and won't start

**To Reproduce**
Launch Discord with the plugin enabled

**Screenshots**
![Activity Icons crash log](https://github.com/Neodymium7/BetterDiscordStuff/assets/139889891/605ee571-fd01-479a-a492-65aec07ad1d0)
![Activityiscons load error](https://github.com/Neodymium7/BetterDiscordStuff/assets/139889891/e1d8b812-65d6-4f0d-827f-9cede7cbce83)

**Additional context**
```
Error: Module 'ActivityStatus' not found.
	
	Contact the plugin developer to inform them of this error.
    at expectModule (betterdiscord://plugins/ActivityIcons.plugin.js:116:11)
    at eval (betterdiscord://plugins/ActivityIcons.plugin.js:175:26)
    at buildPlugin (betterdiscord://plugins/ActivityIcons.plugin.js:601:4)
    at eval (betterdiscord://plugins/ActivityIcons.plugin.js:606:46)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

**Comment by RobertoGol** [comment]
This is it?

	Contact the plugin developer to inform them of this error.
    at expectModule (betterdiscord://plugins/ActivityIcons.plugin.js:116:11)
    at eval (betterdiscord://plugins/ActivityIcons.plugin.js:175:26)
    at buildPlugin (betterdiscord://plugins/ActivityIcons.plugin.js:601:4)
    at eval (betterdiscord://plugins/ActivityIcons.plugin.js:606:46)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.reloadAddon (betterdiscord/renderer.js:5:7111)
    at betterdiscord/renderer.js:5:4235

**Comment by ottocolten** [comment]
Yea, it must've been with the new discord update; half of my plugins are broken and wont activate. :/
