### ISSUE TITLE
Module not found, could not be compiled

### ISSUE THREAD

**Issue by NoahRoters** [Neodymium7/BetterDiscordStuff#67]
# **Addon Name and Version**
TypingUserPopouts v1.3.4

# **Discord Version**
Stable 303557 (3b02892) 
Host 1.0.9151 x64 (48891) 
Build Override: N/A Windows 10 64-bit (10.0.19045)

# **Bug:**
```
Error: Module 'TypingUsersContainer' not found.
	Contact the plugin developer to inform them of this error.
    at expectModule (betterdiscord://plugins/TypingUsersPopouts.plugin.js:119:11)
    at eval (betterdiscord://plugins/TypingUsersPopouts.plugin.js:146:32)
    at buildPlugin (betterdiscord://plugins/TypingUsersPopouts.plugin.js:232:4)
    at eval (betterdiscord://plugins/TypingUsersPopouts.plugin.js:237:46)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201
```
(At the start of Discord)

# **To Reproduce**
Install BD, install the plugin and start DC.

**Screenshots**
![image](https://github.com/Neodymium7/BetterDiscordStuff/assets/143958735/f326fec5-6770-45a2-b2e3-5a9a5c6c8cbe)
![image](https://github.com/Neodymium7/BetterDiscordStuff/assets/143958735/680e605f-95e0-47d8-b137-ee8995b64e99)

The bughas been present since the new update of Discord
thanks in advance for the fix.

**Comment by treymur** [comment]
He just released a fix on github, I don't think the update is on BD yet. You'll have to download the TypingUsersPopout.plugin.js file from the repo.

Can't say for this plugin but similar issues happened with VoiceActivity and ActivityIcons, which the github fix solved.

**Comment by NoahRoters** [comment]
Hey, thanks for that.
One plugin less with issues :)
